### ISSUE TITLE
msg is not cloned for multiple event handlers

### ISSUE THREAD

**Issue by 2WeltenChris** [TotallyInformation/node-red-contrib-events#1]
Hi Julian,

first: great idea with the event nodes! Actually we just started with something quite similar when we stumbled upon your solution. :)

After a quick test I found a small bug though: When you have more than one `event in` node reacting to a specific event, changes on the `msg` object in one flow mean that the `msg` object also changes in the other.

Take the following flow for example:

`[
    {
        "id": "b3bb2a05cbac7ed0",
        "type": "tab",
        "label": "parallel",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "5c3c11eea10385cb",
        "type": "inject",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 100,
        "wires": [
            [
                "093b13a14d9ef0f2"
            ]
        ]
    },
    {
        "id": "093b13a14d9ef0f2",
        "type": "event-out",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "topic": "test",
        "passthrough": "none",
        "outputs": 0,
        "x": 350,
        "y": 100,
        "wires": []
    },
    {
        "id": "bdee882c91f697de",
        "type": "event-in",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "topic": "test",
        "x": 130,
        "y": 220,
        "wires": [
            [
                "083ac3446a69ab30"
            ]
        ]
    },
    {
        "id": "ca8d0c76cd7787eb",
        "type": "debug",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 550,
        "y": 220,
        "wires": []
    },
    {
        "id": "6168bcc64f5a949c",
        "type": "event-in",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "topic": "test",
        "x": 130,
        "y": 320,
        "wires": [
            [
                "d686424c67e9664b"
            ]
        ]
    },
    {
        "id": "5a80987aef35ac30",
        "type": "debug",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 550,
        "y": 320,
        "wires": []
    },
    {
        "id": "083ac3446a69ab30",
        "type": "change",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "first",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 330,
        "y": 220,
        "wires": [
            [
                "ca8d0c76cd7787eb"
            ]
        ]
    },
    {
        "id": "d686424c67e9664b",
        "type": "change",
        "z": "b3bb2a05cbac7ed0",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "second",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 330,
        "y": 320,
        "wires": [
            [
                "5a80987aef35ac30"
            ]
        ]
    }
]`

It is expected that the one (sub-) flow prints "first" and the second prints "second". But as the `msg` object is altered in between, both times "second" gets printed.

The solution in my opinion would be to first collect all relevent event handlers and then clone the `msg` object accordingly before one (cloned) `msg` object gets passed to one `event in` node.

Hope this helps!

Cheers, Chris

**Comment by mverboom** [comment]
Great to see it's not just me :). Love the event nodes, but ran into the same issue. Manually put some cloning nodes into my flows, but would be great if it would be integrated.

Regards,

Mark

**Comment by TotallyInformation** [comment]
PR now merged. Many thanks for your contribution. 🙂
